environment:
  development:
    serverurl:
    secretid: gema/dev
    appsettings: debug
    tmpfolder: E:/Jenkins/tmp
  quality:
    serverurl: wngplgmaappwq00.itauchile.cl
    secretid: gema/qa
    appsettings: qa
    tmpfolder: E:/Jenkins/tmp
  production:
    serverurl: wngplgmaappwp00.itauchile.cl
    secretid: gema/production
    appsettings: release
    tmpfolder: E:/Jenkins/tmp
